/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSecretsIndexRouteImport } from './routes/_app/secrets/index'
import { Route as AppRolloutsIndexRouteImport } from './routes/_app/rollouts/index'
import { Route as AppPackagesIndexRouteImport } from './routes/_app/packages/index'
import { Route as AppOpsIndexRouteImport } from './routes/_app/ops/index'
import { Route as AppHistoryIndexRouteImport } from './routes/_app/history/index'
import { Route as AppFleetIndexRouteImport } from './routes/_app/fleet/index'
import { Route as AppEnrollmentIndexRouteImport } from './routes/_app/enrollment/index'
import { Route as AppDevicesIndexRouteImport } from './routes/_app/devices/index'
import { Route as AppDeployIndexRouteImport } from './routes/_app/deploy/index'
import { Route as AppSecretsSetRouteImport } from './routes/_app/secrets/set'
import { Route as AppRolloutsNewRouteImport } from './routes/_app/rollouts/new'
import { Route as AppRolloutsRolloutIdRouteImport } from './routes/_app/rollouts/$rollout-id'
import { Route as AppPackagesNewRouteImport } from './routes/_app/packages/new'
import { Route as AppEnrollmentNewRouteImport } from './routes/_app/enrollment/new'
import { Route as AppDevicesDeviceIdIndexRouteImport } from './routes/_app/devices/$device-id/index'
import { Route as AppPackagesNameVersionRouteImport } from './routes/_app/packages/$name.$version'
import { Route as AppOpsTierTokensNewRouteImport } from './routes/_app/ops/tier-tokens/new'
import { Route as AppDevicesDeviceIdEditRouteImport } from './routes/_app/devices/$device-id/edit'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSecretsIndexRoute = AppSecretsIndexRouteImport.update({
  id: '/secrets/',
  path: '/secrets/',
  getParentRoute: () => AppRoute,
} as any)
const AppRolloutsIndexRoute = AppRolloutsIndexRouteImport.update({
  id: '/rollouts/',
  path: '/rollouts/',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesIndexRoute = AppPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => AppRoute,
} as any)
const AppOpsIndexRoute = AppOpsIndexRouteImport.update({
  id: '/ops/',
  path: '/ops/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryIndexRoute = AppHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetIndexRoute = AppFleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => AppRoute,
} as any)
const AppEnrollmentIndexRoute = AppEnrollmentIndexRouteImport.update({
  id: '/enrollment/',
  path: '/enrollment/',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesIndexRoute = AppDevicesIndexRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => AppRoute,
} as any)
const AppDeployIndexRoute = AppDeployIndexRouteImport.update({
  id: '/deploy/',
  path: '/deploy/',
  getParentRoute: () => AppRoute,
} as any)
const AppSecretsSetRoute = AppSecretsSetRouteImport.update({
  id: '/secrets/set',
  path: '/secrets/set',
  getParentRoute: () => AppRoute,
} as any)
const AppRolloutsNewRoute = AppRolloutsNewRouteImport.update({
  id: '/rollouts/new',
  path: '/rollouts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRolloutsRolloutIdRoute = AppRolloutsRolloutIdRouteImport.update({
  id: '/rollouts/$rollout-id',
  path: '/rollouts/$rollout-id',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesNewRoute = AppPackagesNewRouteImport.update({
  id: '/packages/new',
  path: '/packages/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEnrollmentNewRoute = AppEnrollmentNewRouteImport.update({
  id: '/enrollment/new',
  path: '/enrollment/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesDeviceIdIndexRoute = AppDevicesDeviceIdIndexRouteImport.update({
  id: '/devices/$device-id/',
  path: '/devices/$device-id/',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesNameVersionRoute = AppPackagesNameVersionRouteImport.update({
  id: '/packages/$name/$version',
  path: '/packages/$name/$version',
  getParentRoute: () => AppRoute,
} as any)
const AppOpsTierTokensNewRoute = AppOpsTierTokensNewRouteImport.update({
  id: '/ops/tier-tokens/new',
  path: '/ops/tier-tokens/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesDeviceIdEditRoute = AppDevicesDeviceIdEditRouteImport.update({
  id: '/devices/$device-id/edit',
  path: '/devices/$device-id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/enrollment/new': typeof AppEnrollmentNewRoute
  '/packages/new': typeof AppPackagesNewRoute
  '/rollouts/$rollout-id': typeof AppRolloutsRolloutIdRoute
  '/rollouts/new': typeof AppRolloutsNewRoute
  '/secrets/set': typeof AppSecretsSetRoute
  '/deploy/': typeof AppDeployIndexRoute
  '/devices/': typeof AppDevicesIndexRoute
  '/enrollment/': typeof AppEnrollmentIndexRoute
  '/fleet/': typeof AppFleetIndexRoute
  '/history/': typeof AppHistoryIndexRoute
  '/ops/': typeof AppOpsIndexRoute
  '/packages/': typeof AppPackagesIndexRoute
  '/rollouts/': typeof AppRolloutsIndexRoute
  '/secrets/': typeof AppSecretsIndexRoute
  '/devices/$device-id/edit': typeof AppDevicesDeviceIdEditRoute
  '/ops/tier-tokens/new': typeof AppOpsTierTokensNewRoute
  '/packages/$name/$version': typeof AppPackagesNameVersionRoute
  '/devices/$device-id/': typeof AppDevicesDeviceIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/': typeof AppIndexRoute
  '/enrollment/new': typeof AppEnrollmentNewRoute
  '/packages/new': typeof AppPackagesNewRoute
  '/rollouts/$rollout-id': typeof AppRolloutsRolloutIdRoute
  '/rollouts/new': typeof AppRolloutsNewRoute
  '/secrets/set': typeof AppSecretsSetRoute
  '/deploy': typeof AppDeployIndexRoute
  '/devices': typeof AppDevicesIndexRoute
  '/enrollment': typeof AppEnrollmentIndexRoute
  '/fleet': typeof AppFleetIndexRoute
  '/history': typeof AppHistoryIndexRoute
  '/ops': typeof AppOpsIndexRoute
  '/packages': typeof AppPackagesIndexRoute
  '/rollouts': typeof AppRolloutsIndexRoute
  '/secrets': typeof AppSecretsIndexRoute
  '/devices/$device-id/edit': typeof AppDevicesDeviceIdEditRoute
  '/ops/tier-tokens/new': typeof AppOpsTierTokensNewRoute
  '/packages/$name/$version': typeof AppPackagesNameVersionRoute
  '/devices/$device-id': typeof AppDevicesDeviceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/enrollment/new': typeof AppEnrollmentNewRoute
  '/_app/packages/new': typeof AppPackagesNewRoute
  '/_app/rollouts/$rollout-id': typeof AppRolloutsRolloutIdRoute
  '/_app/rollouts/new': typeof AppRolloutsNewRoute
  '/_app/secrets/set': typeof AppSecretsSetRoute
  '/_app/deploy/': typeof AppDeployIndexRoute
  '/_app/devices/': typeof AppDevicesIndexRoute
  '/_app/enrollment/': typeof AppEnrollmentIndexRoute
  '/_app/fleet/': typeof AppFleetIndexRoute
  '/_app/history/': typeof AppHistoryIndexRoute
  '/_app/ops/': typeof AppOpsIndexRoute
  '/_app/packages/': typeof AppPackagesIndexRoute
  '/_app/rollouts/': typeof AppRolloutsIndexRoute
  '/_app/secrets/': typeof AppSecretsIndexRoute
  '/_app/devices/$device-id/edit': typeof AppDevicesDeviceIdEditRoute
  '/_app/ops/tier-tokens/new': typeof AppOpsTierTokensNewRoute
  '/_app/packages/$name/$version': typeof AppPackagesNameVersionRoute
  '/_app/devices/$device-id/': typeof AppDevicesDeviceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/enrollment/new'
    | '/packages/new'
    | '/rollouts/$rollout-id'
    | '/rollouts/new'
    | '/secrets/set'
    | '/deploy/'
    | '/devices/'
    | '/enrollment/'
    | '/fleet/'
    | '/history/'
    | '/ops/'
    | '/packages/'
    | '/rollouts/'
    | '/secrets/'
    | '/devices/$device-id/edit'
    | '/ops/tier-tokens/new'
    | '/packages/$name/$version'
    | '/devices/$device-id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/'
    | '/enrollment/new'
    | '/packages/new'
    | '/rollouts/$rollout-id'
    | '/rollouts/new'
    | '/secrets/set'
    | '/deploy'
    | '/devices'
    | '/enrollment'
    | '/fleet'
    | '/history'
    | '/ops'
    | '/packages'
    | '/rollouts'
    | '/secrets'
    | '/devices/$device-id/edit'
    | '/ops/tier-tokens/new'
    | '/packages/$name/$version'
    | '/devices/$device-id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/'
    | '/_app/enrollment/new'
    | '/_app/packages/new'
    | '/_app/rollouts/$rollout-id'
    | '/_app/rollouts/new'
    | '/_app/secrets/set'
    | '/_app/deploy/'
    | '/_app/devices/'
    | '/_app/enrollment/'
    | '/_app/fleet/'
    | '/_app/history/'
    | '/_app/ops/'
    | '/_app/packages/'
    | '/_app/rollouts/'
    | '/_app/secrets/'
    | '/_app/devices/$device-id/edit'
    | '/_app/ops/tier-tokens/new'
    | '/_app/packages/$name/$version'
    | '/_app/devices/$device-id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/secrets/': {
      id: '/_app/secrets/'
      path: '/secrets'
      fullPath: '/secrets/'
      preLoaderRoute: typeof AppSecretsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rollouts/': {
      id: '/_app/rollouts/'
      path: '/rollouts'
      fullPath: '/rollouts/'
      preLoaderRoute: typeof AppRolloutsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages/': {
      id: '/_app/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof AppPackagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ops/': {
      id: '/_app/ops/'
      path: '/ops'
      fullPath: '/ops/'
      preLoaderRoute: typeof AppOpsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history/': {
      id: '/_app/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof AppHistoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet/': {
      id: '/_app/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof AppFleetIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enrollment/': {
      id: '/_app/enrollment/'
      path: '/enrollment'
      fullPath: '/enrollment/'
      preLoaderRoute: typeof AppEnrollmentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices/': {
      id: '/_app/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof AppDevicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deploy/': {
      id: '/_app/deploy/'
      path: '/deploy'
      fullPath: '/deploy/'
      preLoaderRoute: typeof AppDeployIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/secrets/set': {
      id: '/_app/secrets/set'
      path: '/secrets/set'
      fullPath: '/secrets/set'
      preLoaderRoute: typeof AppSecretsSetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rollouts/new': {
      id: '/_app/rollouts/new'
      path: '/rollouts/new'
      fullPath: '/rollouts/new'
      preLoaderRoute: typeof AppRolloutsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rollouts/$rollout-id': {
      id: '/_app/rollouts/$rollout-id'
      path: '/rollouts/$rollout-id'
      fullPath: '/rollouts/$rollout-id'
      preLoaderRoute: typeof AppRolloutsRolloutIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages/new': {
      id: '/_app/packages/new'
      path: '/packages/new'
      fullPath: '/packages/new'
      preLoaderRoute: typeof AppPackagesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enrollment/new': {
      id: '/_app/enrollment/new'
      path: '/enrollment/new'
      fullPath: '/enrollment/new'
      preLoaderRoute: typeof AppEnrollmentNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices/$device-id/': {
      id: '/_app/devices/$device-id/'
      path: '/devices/$device-id'
      fullPath: '/devices/$device-id/'
      preLoaderRoute: typeof AppDevicesDeviceIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/packages/$name/$version': {
      id: '/_app/packages/$name/$version'
      path: '/packages/$name/$version'
      fullPath: '/packages/$name/$version'
      preLoaderRoute: typeof AppPackagesNameVersionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ops/tier-tokens/new': {
      id: '/_app/ops/tier-tokens/new'
      path: '/ops/tier-tokens/new'
      fullPath: '/ops/tier-tokens/new'
      preLoaderRoute: typeof AppOpsTierTokensNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices/$device-id/edit': {
      id: '/_app/devices/$device-id/edit'
      path: '/devices/$device-id/edit'
      fullPath: '/devices/$device-id/edit'
      preLoaderRoute: typeof AppDevicesDeviceIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppEnrollmentNewRoute: typeof AppEnrollmentNewRoute
  AppPackagesNewRoute: typeof AppPackagesNewRoute
  AppRolloutsRolloutIdRoute: typeof AppRolloutsRolloutIdRoute
  AppRolloutsNewRoute: typeof AppRolloutsNewRoute
  AppSecretsSetRoute: typeof AppSecretsSetRoute
  AppDeployIndexRoute: typeof AppDeployIndexRoute
  AppDevicesIndexRoute: typeof AppDevicesIndexRoute
  AppEnrollmentIndexRoute: typeof AppEnrollmentIndexRoute
  AppFleetIndexRoute: typeof AppFleetIndexRoute
  AppHistoryIndexRoute: typeof AppHistoryIndexRoute
  AppOpsIndexRoute: typeof AppOpsIndexRoute
  AppPackagesIndexRoute: typeof AppPackagesIndexRoute
  AppRolloutsIndexRoute: typeof AppRolloutsIndexRoute
  AppSecretsIndexRoute: typeof AppSecretsIndexRoute
  AppDevicesDeviceIdEditRoute: typeof AppDevicesDeviceIdEditRoute
  AppOpsTierTokensNewRoute: typeof AppOpsTierTokensNewRoute
  AppPackagesNameVersionRoute: typeof AppPackagesNameVersionRoute
  AppDevicesDeviceIdIndexRoute: typeof AppDevicesDeviceIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppEnrollmentNewRoute: AppEnrollmentNewRoute,
  AppPackagesNewRoute: AppPackagesNewRoute,
  AppRolloutsRolloutIdRoute: AppRolloutsRolloutIdRoute,
  AppRolloutsNewRoute: AppRolloutsNewRoute,
  AppSecretsSetRoute: AppSecretsSetRoute,
  AppDeployIndexRoute: AppDeployIndexRoute,
  AppDevicesIndexRoute: AppDevicesIndexRoute,
  AppEnrollmentIndexRoute: AppEnrollmentIndexRoute,
  AppFleetIndexRoute: AppFleetIndexRoute,
  AppHistoryIndexRoute: AppHistoryIndexRoute,
  AppOpsIndexRoute: AppOpsIndexRoute,
  AppPackagesIndexRoute: AppPackagesIndexRoute,
  AppRolloutsIndexRoute: AppRolloutsIndexRoute,
  AppSecretsIndexRoute: AppSecretsIndexRoute,
  AppDevicesDeviceIdEditRoute: AppDevicesDeviceIdEditRoute,
  AppOpsTierTokensNewRoute: AppOpsTierTokensNewRoute,
  AppPackagesNameVersionRoute: AppPackagesNameVersionRoute,
  AppDevicesDeviceIdIndexRoute: AppDevicesDeviceIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
