/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { DeployLogOutcome } from './deploy-log-outcome';
import type { DeployLogPhase } from './deploy-log-phase';

/**
 * The agent's upload body: one captured compose run for one
 * deployment. `text` is the combined stdout+stderr the agent
 * captured; `truncated` is true when the agent already clipped it to
 * its own cap before sending (the server additionally rejects bodies
 * over its accept cap).
 */
export interface DeployLogUpload {
  /** The application id (Margo `applicationId`) for display grouping. */
  appId: string;
  /**
     * When the agent captured this run (RFC 3339, device clock —
     * preserved verbatim like the journal's `observedAt`).
     */
  capturedAt: string;
  /**
     * The Margo deployment id this run converged (same value the
     * device reports in `DeploymentStatusManifest.deploymentId`).
     */
  deploymentId: string;
  /**
     * Process exit code when known (`None` if the agent never got one
     * — e.g. the binary could not be spawned).
     * @nullable
     */
  exitCode?: number | null;
  outcome: DeployLogOutcome;
  phase: DeployLogPhase;
  /** Combined captured output (stdout+stderr). Plain text. */
  text: string;
  /** True if the agent clipped `text` before upload. */
  truncated: boolean;
}
