/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * What the converge attempt this log covers resulted in — mirrors the
 * agent's per-deployment outcome, independent of the Margo state.
 */
export type DeployLogOutcome = typeof DeployLogOutcome[keyof typeof DeployLogOutcome];


export const DeployLogOutcome = {
  applied: 'applied',
  failed: 'failed',
  removed: 'removed',
} as const;
