/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Which compose phase produced this output.
 */
export type DeployLogPhase = typeof DeployLogPhase[keyof typeof DeployLogPhase];


export const DeployLogPhase = {
  up: 'up',
  down: 'down',
} as const;
