/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { DeployLogMeta } from './deploy-log-meta';

/**
 * GET-one response: metadata + the full text. (The route MAY also
 * serve raw `text/plain`; this is the JSON shape the UI consumes.)
 */
export interface DeployLogContent {
  meta: DeployLogMeta;
  text: string;
}
