/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { DeployLogOutcome } from './deploy-log-outcome';
import type { DeployLogPhase } from './deploy-log-phase';

/**
 * Listing/reference metadata for one stored log — everything the UI
 * needs for a list row, minus the (potentially large) text body,
 * which is fetched on demand by `id`.
 */
export interface DeployLogMeta {
  appId: string;
  /** The device-captured RFC 3339 timestamp, preserved verbatim. */
  capturedAt: string;
  deploymentId: string;
  /** Opaque server-assigned log id (the handle for the GET-one route). */
  id: string;
  outcome: DeployLogOutcome;
  phase: DeployLogPhase;
  /**
     * Byte length of the stored text.
     * @minimum 0
     */
  sizeBytes: number;
  truncated: boolean;
}
